// Code generated by protoc-gen-thrift.
// source: hello.proto
// DO NOT EDIT!

/*
This thrift interface description was generated from from one more protobuf descriptors.

It is generated from these files:
	hello.proto

It has these top-level structs:
	HelloRequest
	HelloReply
*/
namespace go hello

// The request message containing the user's name.
struct HelloRequest {
	1:	optional HelloRequestArg	arg,
	2:	optional list<i32>	ints,
	3:	optional map<i32,i32>	amap,
}

union HelloRequestArg {
	1:	string name,
	2:	i32 age,
	3:	HelloReply blip,
}
// The response message containing the greetings
struct HelloReply {
	1:	optional string	message,
	2:	optional i32	integer,
	3:	optional bool	bloop,
}

service Greeter {
	// Sends a greeting
	HelloReply SayHello(1: HelloRequest in),
}

